baseURL: "https://arlundborg.com"
title: Anton Rask Lundborg
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
        - name: Teaching
          url: teaching/
        

params:
    description: "This is the personal website of Anton Rask Lundborg, 
    # Tenure-track Assistant Professor of Statistics at the Department of
    # Mathematical Sciences, University of Copenhagen."
    author: Anton Rask Lundborg
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Research", "Teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Anton Rask Lundborg
          subtitle: |
            I am a Tenure-track Assistant Professor of Statistics at
            the Department of Mathematical Sciences at the University of 
            Copenhagen, Denmark. I am also a member of the Copenhagen Causality
            Lab.
            <br><br>
            My research involves the development and mathematical analysis of 
            practical and flexible statistical methods. A central theme of my 
            work is the application of non- and semiparametric techniques, 
            especially in the context of causal inference. My experience also
            includes the analysis of non-Euclidean data.
        
          imageUrl: "prof_pic.jpg"
          imageWidth: 287
          imageHeight: 413
          # buttons:
          #   - name: Research
          #     url: research/
          #   - name: Teaching
          #     url: teaching/

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:arl@math.ku.dk
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=8vP4lJQAAAAJ
        - name: GitHub
          url: https://github.com/ARLundborg
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social
        - name: arxiv
          url: http://arxiv.org/a/lundborg_a_1 
        - name: orcid
          url: https://orcid.org/0000-0001-5565-5678

    assets:
        disableScrollBarStyle: true
        favicon: "none"
        favicon16x16: "none"
        favicon32x32: "none"
        apple_touch_icon: "none"
        safari_pinned_tab: "none"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Anton Rask Lundborg"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2